language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - '10'
  - '11'
  - '8'
script:
  - yarn run test:prod && yarn run build
after_success:
  - yarn run travis-deploy-once "yarn run report-coverage"
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn run travis-deploy-once "yarn run deploy-docs"; fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
